# Generated by Django 4.0.3 on 2022-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocompany', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
